### ISSUE TITLE
Broken Integration Tests 

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#1595]
**Describe the bug**

Broken integration tests on Master branch

![image](https://user-images.githubusercontent.com/49491949/143883882-45330f82-cda7-4da3-9588-a175a3191816.png)

**Expected behavior**

All Integration tests should pass

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Zowe Explorer Version:
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

**Comment by t1m0thyj** [comment]
Reopening since integration tests are still broken.

Some suggestions for when we fix them in the future:
* Add "npx" in front of ts-node commands to remove requirement of global ts-node install
* Install and configure [mocha-junit-reporter](https://www.npmjs.com/package/mocha-junit-reporter) so we can collect test metrics
* Update instructions in README-Developer.md as needed
