### ISSUE TITLE
The paste also does not trigger 'safe save' and automatically saves the contents to the mainframe

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-explorer-vscode#2052]

**Comment by traeok** [comment]
Regarding this issue and the one it is tracking (#395) :

Isn't this the intended behavior? In the second GIF the issue creator is performing a different action than the copy/paste data set functionality. They are calling the "Copy" shortcut through the browser (instead of Ctrl+C) which is copying the line where their cursor is - And then when they click "Paste," it pastes that line underneath the other line in that dataset, which would be expected output.

**Comment by zFernand0** [comment]
🤯 I honestly didn't know it worked like that 🤯 
I kind of agree with your assessment though.
We can close this issue if we think there shouldn't be a confirmation (safe save) when saving to an existing sequential dataset (PS) 😋

**Comment by traeok** [comment]
@zFernand0 I think in this situation the behavior was a result of the `pasteMember` implementation, as the PS nodes are interpreted as members. But, I can understand why the user expects the commands to append the contents to the other node, as the command names might suggest.

In hindsight, it seems that this situation can't be reproduced anymore - I tried to copy a PS dataset to reproduce the issue, but the paste option no longer shows up when I right-click on another PS node after the copy operation.

**Comment by JillieBeanSim** [comment]
@zFernand0 can we close this as intended behavior? or should we create a confirmation for users?

**Comment by zFernand0** [comment]
Hey Billie, 
thanks for the nudge.
I do think this can be closed :yum:
