### ISSUE TITLE
Auto-size columns in table views

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-explorer-vscode#3054]
**Is your feature request related to a problem? Please describe.**

Some columns are wider than they need to be.

**Describe the solution you'd like**

By automatically sizing columns in table views based on the column title and the values in each row, users would be able to see more information without scrolling horizontally.

**Describe alternatives you've considered**

**Additional context**

**Comment by traeok** [comment]
Hi @adam-wolfe,

Just wanted to verify that this is for the jobs tabular view? I've adjusted the behavior so that columns are auto-sized in commit [75ae08c](https://github.com/zowe/zowe-explorer-vscode/pull/3050/commits/75ae08c147abf1da3af50b7806a021bb6cb0c012). Developers can specify the `autoSizeStrategy: { type: "fitCellContents" }` property to the options function on the TableBuilder to automatically resize columns to fit cell contents.
