### ISSUE TITLE
IApiRegisterClient.onProfilesUpdate() does not work

### ISSUE THREAD

**Issue by FrankSu1996** [zowe/zowe-explorer-vscode#3078]
**Describe the bug**

IApiRegisterClient.onProfilesUpdate() does not work. Our extension uses it currently to detect team config creation/deletion events. We are using our own vscode file watcher to detect change events, because previously onProfilesUpdate() was not robust for changes in the secure properties. I know when we first adopted it, things were working ok. However, currently, using zowe-explorer-api 2.17.0 (also tried with 2.16.0), the event listener barely works. It might detect an event maybe 1/10 times, but mostly will fail to fire for any sort of team config changes. Note that when I test with our own vscode file watcher for the same create/update/delete events, they always fire.

**To Reproduce**
1. have extension call IApiRegisterClient.onProfilesUpdate()
2. Create/delete/change a zowe team config file. Doesn't matter if global or project level.

**Expected behavior**

onProfilesUpdate() should fire with corresponding event, but doesn't

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Zowe Explorer Version: v3.0.0-next.202404242037
- (Optional) Are you using Secure Credential Store? yes
- zowe-explorer-api v2.17.0

**Additional context**

**Comment by FrankSu1996** [comment]
https://github.com/user-attachments/assets/37157aaa-d22b-40ef-a7a6-54ea8a635465

screen capture showing how the vscode watchers do get triggered, but not onProfilesUpdate()

**Comment by FrankSu1996** [comment]
There are alot of breaking changes from v2-v3 which I haven't had time to fix. Some things, like EventTypes seem to be missing altogether when I try v3 pre-release.

**Comment by FrankSu1996** [comment]
Thanks, as a side note. I noticed zowe/cli is not a dependency anymore for zowe-explorer-api v3. Was this intended? We depend on a method zowe.getImperativeConfig() from zowe/cli when creating team configs. It would be nice if zowe/cli could be kept as a dependency, otherwise we would have to install it ourselves. This might lead to some unintended side effects if our zowe/cli version is different than the ones ZE/api uses.

**Comment by traeok** [comment]
> Thanks, as a side note. I noticed zowe/cli is not a dependency anymore for zowe-explorer-api v3. Was this intended? We depend on a method zowe.getImperativeConfig() from zowe/cli when creating team configs. It would be nice if zowe/cli could be kept as a dependency, otherwise we would have to install it ourselves. This might lead to some unintended side effects if our zowe/cli version is different than the ones ZE/api uses.

Sorry for the delay @FrankSu1996 - this change was intentional and was done in #2730 to avoid pulling in some of the CLI-specific code (that's in the CLI package and unused in ZE API). I do understand your concern though regarding the creation of team configs. However, you will still be able import the `imperative` namespace from Zowe Explorer API and can leverage the `imperative.Config` class to load and save new team configs. But if you rely on information from the `getImperativeConfig` function, we might have to expose this within the Imperative namespace so that extenders can still access it moving forward. 

If you don't mind me asking, what information are you currently leveraging from `getImperativeConfig`? We might be able to provide alternatives depending on what properties you are referencing.

**Comment by traeok** [comment]
In v3, we no longer use the `zowe.getImperativeConfig` function within `Profiles.createZoweSchema`. That said, that does sound inconvenient and I think extenders should get access to this feature out of the box. I'll create an issue to track this - thanks for the heads up.
