### ISSUE TITLE
Implement CircleCI pipeline

### ISSUE THREAD

**Issue by VitGottwald** [zowe/zowe-explorer-vscode#814]
In the past weeks we have experienced many CI outages. This was mainly due to the CI
being overloaded by other product builds, but there were also other issues.

Since our project is open source, there is a number of hosted CI services available free
of charge. 

Let's explore CircleCI. It has been previously approved by the Open Mainframe Project
for some projects. And it follows a configuration as a code model. Server
configuration is not needed. Pipeline is fully configured in the repository through
a yaml file.

**Comment by dkelosky** [comment]
It would be nice to use a hosted solution since most are free.  What would you think about GitHub actions or Azure instead?  It seems like CircleCI doesn't allow for running on Mac OS in their free tier 😞.

**Comment by VitGottwald** [comment]
I am open to any hosted CI that follows configuration as code.

**Comment by jellypuno** [comment]
@MarkAckert Can you weigh in on this?

**Comment by VitGottwald** [comment]
I personally have good experience with CircleCI and currently our CI does not run on Mac anyway so I do not see it as a big problem. But we can reevaluate this at any time and check other solutions as well.

**Comment by MarkAckert** [comment]
I believe CircleCI and Github Actions are both OK. However, since you already have Jenkinsfile written - please consider migrating to https://jenkins.zowe.org/ .  This is a dedicated Jenkins instance LF provides, and agents are provisioned on demand from AWS cloud so there should be no outages.

Using LF Jenkins requires a new YAML entry in https://github.com/zowe/ci-management/tree/master/jjb/zowe and small modification of Jenkinsfile.

Jenkinsfile change:
`node('ca-jenkins-agent') {` -> `node ('ubuntu1804-docker-4c-4g') { docker.image(yourimage).inside {`

**Comment by VitGottwald** [comment]
Thank you @MarkAckert ! I think this is also an opportunity for the team to get some experience with other CI tools to be able to compare them and see the strengths of various solutions.

I think this is valuable on its own and can help us design a better pipelines in the end regardless of where we run them.

**Comment by t1m0thyj** [comment]
We have settled on using GitHub Actions
